recognize_filemanager:
    security:
        actions:
            open: [ ROLE_USER ]
            upload: [ ROLE_USER ]
            create: [ ROLE_ADMIN ]
            move: [ ROLE_ADMIN ]
            rename: [ ROLE_ADMIN ]
            delete: [ ROLE_ADMIN ]