recognize_filemanager:
    directories:
        default: /var/www/Filemanager/app/cache
        user: /dev/null

    api_paths:
        read: _fileapi_read
        create: _fileapi_create
        upload: _fileapi_create
        rename: _fileapi_rename
        move: _fileapi_move
        delete: _fileapi_delete
        download: _fileapi_download
        preview: _fileapi_preview

    access_control:
        - { path: ^/, directory: default, roles: [ ROLE_USER ], actions: [ open, upload, create, move, rename, delete ] }