services:
    recognize.filemanager.twig.filemanager_extension:
        class: Recognize\FilemanagerBundle\Twig\FilemanagerExtension
        arguments: [@service_container, %recognize_filemanager.config%]
        public: false
        tags:
             - { name: twig.extension }

    recognize.filemanager.form.type.filereference:
        class: Recognize\FilemanagerBundle\Form\Type\FileReferenceType
        arguments: [@recognize.file_manager, @recognize.filedata_synchronizer]
        tags:
            -  { name: form.type, alias: "filereference" }

    recognize.filemanager_directory_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Recognize\FilemanagerBundle\Entity\Directory

    recognize.filemanager_file_repository:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.default_entity_manager
            factory_method: getRepository
            arguments:
                - Recognize\FilemanagerBundle\Entity\FileReference

    recognize.file_manager:
        class: Recognize\FilemanagerBundle\Service\FilemanagerService
        arguments: [ %recognize_filemanager.config%, @recognize.file_security_context, @recognize.filedata_synchronizer, %kernel.root_dir% ]

    recognize.thumbnail_generator:
        class: Recognize\FilemanagerBundle\Service\ThumbnailGeneratorService
        arguments: [ %recognize_filemanager.config% ]

    recognize.filedata_synchronizer:
        class: Recognize\FilemanagerBundle\Service\FiledataSynchronizer
        arguments: [ @doctrine.orm.entity_manager, @recognize.filemanager_directory_repository, @recognize.filemanager_file_repository, @recognize.file_acl_manager, @recognize.thumbnail_generator ]

    recognize.file_acl_manager:
        class: Recognize\FilemanagerBundle\Service\FileACLManagerService
        arguments: [ @security.acl.provider ]

    recognize.file_security_context:
        class: Recognize\FilemanagerBundle\Security\FileSecurityContext
        arguments: [ %recognize_filemanager.config%, @security.acl.provider, @security.token_storage, @recognize.filemanager_directory_repository ]