services:
    recognize.file_manager:
        class: Recognize\FilemanagerBundle\Service\FilemanagerService
        arguments: [ %recognize_filemanager.config%, @recognize.file_security_context ]
    recognize.file_acl_manager:
        class: Recognize\FilemanagerBundle\Service\FileACLManagerService
        arguments: [ @security.acl.provider, @security.token_storage, @doctrine.orm.entity_manager, @security.context, %recognize_filemanager.config% ]
    recognize.file_security_context:
        class: Recognize\FilemanagerBundle\Security\FileSecurityContext
        arguments: [ %recognize_filemanager.config%, @security.acl.provider, @security.context ]