services:
    recognize.filemanager_directory_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Recognize\FilemanagerBundle\Entity\Directory


    recognize.file_manager:
        class: Recognize\FilemanagerBundle\Service\FilemanagerService
        arguments: [ %recognize_filemanager.config%, @recognize.file_security_context, @recognize.filedata_synchronizer ]
    recognize.filedata_synchronizer:
        class: Recognize\FilemanagerBundle\Service\FiledataSynchronizer
        arguments: [ @doctrine.orm.entity_manager, @recognize.filemanager_directory_repository ]

    recognize.file_acl_manager:
        class: Recognize\FilemanagerBundle\Service\FileACLManagerService
        arguments: [ @security.acl.provider, @security.token_storage, @doctrine.orm.entity_manager, @security.context, %recognize_filemanager.config% ]
    recognize.file_security_context:
        class: Recognize\FilemanagerBundle\Security\FileSecurityContext
        arguments: [ %recognize_filemanager.config%, @security.acl.provider, @security.context, @recognize.filemanager_directory_repository ]